In [59]:
num_stages = 10
num_layers = 30
filter_length = 3
width = 512
skip_width = 256
ae_num_stages = 10
ae_num_layers = 30
ae_filter_length = 3
ae_width = 128

self.num_iters = 200000
self.learning_rate_schedule = {
    0: 2e-4,
    90000: 4e-4 / 3,
    120000: 6e-5,
    150000: 4e-5,
    180000: 2e-5,
    210000: 6e-6,
    240000: 2e-6,
}
self.ae_hop_length = 512
self.ae_bottleneck_width = 16
self.train_path = train_path

In [60]:
4096 // 16000 // 1
reshape to 4096 // 16000 : 2 // 2 // 1
    

In [61]:
import numpy as np

In [103]:
a = np.arange(6*18)

In [104]:
b = a.reshape((6,18))
c = b
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
         31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
         49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107]])

In [106]:
b.reshape([6//3, 3, 18])

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
          30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53]],

       [[ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
          66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         102, 103, 104, 105, 106, 107]]])

In [111]:
d = c.reshape([6, 18//3, 3])
print(d)
d = np.transpose(d, [0,2,1])
print(d)

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]]

 [[ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]
  [ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]]

 [[ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]]

 [[ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]]]
[[[  0   3   6   9  12  15]
  [  1   4   7  10  13  16]
  [  2   5   8  11  14  17]]

 [[ 18  21  24  27  30  33]
  [ 19  22  25  28  31  34]
  [ 20  23  26  29  32  35]]

 [[ 36  39  42  45  48  51]
  [ 37  40  43  46  49  52]
  [ 38  41  44  47  50  53]]

 [[ 54  57  60  63  66  69]
  [ 55  58  61  64  67  70]
  [ 56  59  62  65  68  71]]

 [[ 72  75  78  81  84  87]
  [ 73  76  79  82  85  88]
  [ 74  77  

In [112]:
e = d.reshape([6*3, 18//3])
e

array([[  0,   3,   6,   9,  12,  15],
       [  1,   4,   7,  10,  13,  16],
       [  2,   5,   8,  11,  14,  17],
       [ 18,  21,  24,  27,  30,  33],
       [ 19,  22,  25,  28,  31,  34],
       [ 20,  23,  26,  29,  32,  35],
       [ 36,  39,  42,  45,  48,  51],
       [ 37,  40,  43,  46,  49,  52],
       [ 38,  41,  44,  47,  50,  53],
       [ 54,  57,  60,  63,  66,  69],
       [ 55,  58,  61,  64,  67,  70],
       [ 56,  59,  62,  65,  68,  71],
       [ 72,  75,  78,  81,  84,  87],
       [ 73,  76,  79,  82,  85,  88],
       [ 74,  77,  80,  83,  86,  89],
       [ 90,  93,  96,  99, 102, 105],
       [ 91,  94,  97, 100, 103, 106],
       [ 92,  95,  98, 101, 104, 107]])

In [69]:
import tensorflow as tf
t = tf.constant(e)
paddings = tf.constant([[0,0,], [2, 0]])
# 'constant_values' is 0.
# rank of 't' is 2.
t = tf.pad(t, paddings, "CONSTANT")

with tf.Session() as session:
    res = session.run([t])
    print(res)

[array([[ 0,  0,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  0,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 0,  0, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [ 0,  0, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [ 0,  0, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [ 0,  0, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [ 0,  0, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [ 0,  0, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [ 0,  0, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98],
       [ 0,  0, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])]


## conv1d

samples(nb)?

input size: 
(samples, length_song, channels) -> 

(samples*dilation, length_song // dilation, channels) ->

(samples*dilation, filter_length - 1 + (length_song // dilation), channels) -> 

(samples*dilation, 1, filter_length - 1 + (length_song // dilation), channels)->


kernel size (W): 
(1, filter_length, channels, num_filters)

biases: (num_filters)

strides = [1,1,1,1]



result: 
(samples*dilation, 1, (length_song // dilation), channels)->
(samples*dilation, (length_song // dilation), channels)->
(samples, length_song, channels)->

и връщаме

## pool1d

samplse (mb) ?

input_size: (samples, length_song, channels)

window_shape = [1, 1, window_length, 1]
strides = [1, 1, stride, 1]

x_4d = reshape(x, [samples, 1, length_song, channels])

pooled = pool(x_4d, window_shape, strides, padding=Same)

window_shape(how much we use on a single step)

usually in our case window_shape equals stride

return reshape(pooled, [samples, length_song// stride, num_channels]))


### NN Encoder

en = Conv_1d ((num_filters)ae_width, (filter_length)ae_filter_length)

for num_layer in range(ae_num_layers):

    dilation = 2**(num_layer % ae_num_stages)

    (example:) for nun_layers = 30 and ae_num_stages = 10

    dilation = 1, 2, 2^2, 2^3, ... 2^9, 1, 2 ... , 2^9, 1, 2, ..., 2^9 

    d = relu(en)

    d = conv1d(d, ae_width, ae_filter_length, dilation)

    d = relu(d)

    (this is a residual layer)
    en+= conv1d(d, ae_width, 1(filter_length))

(en before decoding)
en = conv1d(en, ae_bottleneck_width, 1(filter_length)

en = pool1d(en, ae_hop_length, avg_pooling)

### NN Decoder

l = shift_right(original_input)

l = conv1d(l, width, filter_length)  //start convolution

l = conv1d(l, skip_width, 1) // skip_start

for i in range(num_layers):
    dilation = 2 ** (i % num_stages)  //logic is same as dilation in encoder
    
    d = conv1d(l, 2*width, filter_length, dilation)
    
    condition(d, conv1d(en, 2*width, 1))
    
    

#### condition

encoding: [samples, en_length, channels] ->

[samples, en_length, 1, channels]
    
x: [samples, length, channels] ->

reshape: [samples, en_length, -1, channels]
    
    
x+= encoding

x: -> reshape(samples, length, channels)

#### shift_right

input-size: samples, song_length, channels ->

(padding): samples, 1+song_length, channels->

slice using input size shape: 

In [90]:
t = tf.constant([[0,1,2],[0,3,4],[0,5,6]])
# 'constant_values' is 0.
# rank of 't' is 2.
t = tf.slice(t,[0,0], tf.stack([-1,3]))

with tf.Session() as session:
    res = session.run([t])
    print(res)

[array([[0, 1, 2],
       [0, 3, 4],
       [0, 5, 6]])]


slice-> samples, [0, ...(song_length - 1)], channels